"""initial schema

Revision ID: 8f9091f9a055
Revises: 
Create Date: 2026-05-28 16:20:02.441383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9091f9a055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('anchor_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_file_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_url', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('tr', sa.Float(), nullable=False),
    sa.Column('organic_traffic', sa.Integer(), nullable=False),
    sa.Column('ref_domains', sa.Integer(), nullable=False),
    sa.Column('backlinks', sa.Integer(), nullable=False),
    sa.Column('geo', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_domain'), 'donors', ['domain'], unique=False)
    op.create_index(op.f('ix_donors_donor_url'), 'donors', ['donor_url'], unique=True)
    op.create_index(op.f('ix_donors_geo'), 'donors', ['geo'], unique=False)
    op.create_index(op.f('ix_donors_language'), 'donors', ['language'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anchor_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_plan_id', sa.Integer(), nullable=False),
    sa.Column('target_domain', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('anchor_text', sa.String(length=512), nullable=False),
    sa.Column('geo', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('required_link_type', sa.String(length=32), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('selected_donor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_url', sa.String(length=1024), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_plan_id'], ['anchor_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['selected_donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anchor_plan_items_anchor_plan_id'), 'anchor_plan_items', ['anchor_plan_id'], unique=False)
    op.create_index(op.f('ix_anchor_plan_items_assigned_to'), 'anchor_plan_items', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_anchor_plan_items_selected_donor_id'), 'anchor_plan_items', ['selected_donor_id'], unique=False)
    op.create_index(op.f('ix_anchor_plan_items_status'), 'anchor_plan_items', ['status'], unique=False)
    op.create_index(op.f('ix_anchor_plan_items_target_domain'), 'anchor_plan_items', ['target_domain'], unique=False)
    op.create_index(op.f('ix_anchor_plan_items_target_url'), 'anchor_plan_items', ['target_url'], unique=False)
    op.create_table('donor_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('login_password', sa.String(length=255), nullable=False),
    sa.Column('account_username', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_placements', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donor_id', 'account_username', name='uq_donor_account_username')
    )
    op.create_index(op.f('ix_donor_accounts_donor_id'), 'donor_accounts', ['donor_id'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('target_domain', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('donor_url', sa.String(length=512), nullable=False),
    sa.Column('anchor_text', sa.String(length=512), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('donor_account_id', sa.Integer(), nullable=True),
    sa.Column('result_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('login_password', sa.String(length=255), nullable=False),
    sa.Column('account_username', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_plan_item_id'], ['anchor_plan_items.id'], ),
    sa.ForeignKeyConstraint(['donor_account_id'], ['donor_accounts.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_anchor_plan_item_id'), 'placements', ['anchor_plan_item_id'], unique=False)
    op.create_index(op.f('ix_placements_donor_id'), 'placements', ['donor_id'], unique=False)
    op.create_index(op.f('ix_placements_donor_url'), 'placements', ['donor_url'], unique=False)
    op.create_index(op.f('ix_placements_employee_id'), 'placements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_placements_status'), 'placements', ['status'], unique=False)
    op.create_index(op.f('ix_placements_target_domain'), 'placements', ['target_domain'], unique=False)
    op.create_index(op.f('ix_placements_target_url'), 'placements', ['target_url'], unique=False)
    op.create_table('stop_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_domain', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('donor_url', sa.String(length=512), nullable=False),
    sa.Column('anchor_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('placed_by', sa.Integer(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('result_url', sa.String(length=1024), nullable=False),
    sa.Column('anchor_text', sa.String(length=512), nullable=False),
    sa.Column('account_username', sa.String(length=255), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('source_anchor_plan', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_plan_item_id'], ['anchor_plan_items.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['placed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_url', 'donor_url', name='uq_stoplist_url_donor')
    )
    op.create_index(op.f('ix_stop_list_entries_donor_id'), 'stop_list_entries', ['donor_id'], unique=False)
    op.create_index(op.f('ix_stop_list_entries_donor_url'), 'stop_list_entries', ['donor_url'], unique=False)
    op.create_index(op.f('ix_stop_list_entries_target_domain'), 'stop_list_entries', ['target_domain'], unique=False)
    op.create_index(op.f('ix_stop_list_entries_target_url'), 'stop_list_entries', ['target_url'], unique=False)
    op.create_index('ix_stoplist_target_donor', 'stop_list_entries', ['target_url', 'donor_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stoplist_target_donor', table_name='stop_list_entries')
    op.drop_index(op.f('ix_stop_list_entries_target_url'), table_name='stop_list_entries')
    op.drop_index(op.f('ix_stop_list_entries_target_domain'), table_name='stop_list_entries')
    op.drop_index(op.f('ix_stop_list_entries_donor_url'), table_name='stop_list_entries')
    op.drop_index(op.f('ix_stop_list_entries_donor_id'), table_name='stop_list_entries')
    op.drop_table('stop_list_entries')
    op.drop_index(op.f('ix_placements_target_url'), table_name='placements')
    op.drop_index(op.f('ix_placements_target_domain'), table_name='placements')
    op.drop_index(op.f('ix_placements_status'), table_name='placements')
    op.drop_index(op.f('ix_placements_employee_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_donor_url'), table_name='placements')
    op.drop_index(op.f('ix_placements_donor_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_anchor_plan_item_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_donor_accounts_donor_id'), table_name='donor_accounts')
    op.drop_table('donor_accounts')
    op.drop_index(op.f('ix_anchor_plan_items_target_url'), table_name='anchor_plan_items')
    op.drop_index(op.f('ix_anchor_plan_items_target_domain'), table_name='anchor_plan_items')
    op.drop_index(op.f('ix_anchor_plan_items_status'), table_name='anchor_plan_items')
    op.drop_index(op.f('ix_anchor_plan_items_selected_donor_id'), table_name='anchor_plan_items')
    op.drop_index(op.f('ix_anchor_plan_items_assigned_to'), table_name='anchor_plan_items')
    op.drop_index(op.f('ix_anchor_plan_items_anchor_plan_id'), table_name='anchor_plan_items')
    op.drop_table('anchor_plan_items')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_donors_language'), table_name='donors')
    op.drop_index(op.f('ix_donors_geo'), table_name='donors')
    op.drop_index(op.f('ix_donors_donor_url'), table_name='donors')
    op.drop_index(op.f('ix_donors_domain'), table_name='donors')
    op.drop_table('donors')
    op.drop_table('anchor_plans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
